coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true

ignore:
  - "tests/"
  - "demo_localization.py"
  - "scripts/"
  - "*.md"
  - ".github/"

flags:
  unittests:
    paths:
      - "providers/"
      - "handlers/"
      - "commands/"
      - "analytics/"
      - "localization/"
